spring:
  application:
    name: shop-zuul-proxy

zuul:
  ignoredServices: "*"
  routes:
    picture-service:
      path: /picture/**
      sensitiveHeaders:
      serviceId: PICTURE-SERVICE
    stock-service:
      path: /stock/**
      sensitiveHeaders:
      serviceId: STOCK-SERVICE


eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
